pid /tmp/nginx.pid;
error_log /dev/stderr warn;

events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /dev/stdout;

    server {
        listen 127.0.0.1:8080 default_server;

        location / {
            root /srv/webapp;
            try_files $uri $uri/ /index.html;
        }
    }
}
